export const DOCUMENT_RESIZE = 'DOCUMENT_RESIZE'

export const KEY_PRESS = 'KEY_PRESS'

export const LOCATION_CHANGE = 'LOCATION_CHANGE'

export const WINDOW_CHANGE = 'WINDOW_CHANGE'

export const CURRENT_WINDOW_ID = 'CURRENT_WINDOW_ID'